# Generated by Django 3.2.9 on 2021-11-14 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=2500)),
                ('employees', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=75)),
                ('zip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=20)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField(default=0)),
                ('dtype', models.CharField(max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeserver.company')),
            ],
        ),
    ]
