# Generated by Django 3.2.9 on 2021-11-14 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeserver', '0002_alter_history_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=20)),
                ('tweet', models.CharField(max_length=500)),
                ('polarity', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeserver.company')),
            ],
        ),
    ]
