# Generated by Django 3.2.9 on 2021-11-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeserver', '0004_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=100)),
                ('count', models.FloatField()),
                ('buying_price', models.FloatField()),
                ('timestamp', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeserver.company')),
            ],
        ),
    ]
